### ISSUE TITLE
21/02 13:45 Interview RH avec le CIRB  ( @swartz )

### ISSUE THREAD

**Issue by jimmyGoossens** [becodeorg/Lovelace-promo-2#8]

**Comment by pixeline** [comment]
La RH en chef du CIRB viendra partager ses expériences en tant que recruteuse. L'idée est de donner des conseils sur la recherche d'emploi et comment se débrouiller en entretien d'embauche. Ce sera vraiment un atelier trucs et astuces. Ce serait donc intéressant d'encourager vos apprenants à préparer déjà des questions qu'ils souhaiteraient poser sans tabou à une spécialiste du recrutement.
